### ISSUE TITLE
Zamiast pobierać wszystkie filmy, dobrze by było pobierać tylko to co potrzebne. Przy 100 000 filmów może to trochę trwać. Niech baza danych filtruje niepotrzebne rzeczy, pod to jest zoptymalizowana :)

### ISSUE THREAD

**Issue by sebastianleszczynski** [infoshareacademy/jcszr4-HoneyBadgers#32]
Zamiast pobierać wszystkie filmy, dobrze by było pobierać tylko to co potrzebne. Przy 100 000 filmów może to trochę trwać. Niech baza danych filtruje niepotrzebne rzeczy, pod to jest zoptymalizowana :)

_Originally posted by @wisniewski-patryk in https://github.com/infoshareacademy/jcszr4-HoneyBadgers/pull/31#discussion_r803100503_

**Comment by wisniewski-patryk** [comment]
Pewny nie jestem ale chyba tak. @BeataG, mogła byś nas utwierdzić że dobrze myślimy? :Smile:

**Comment by BeataG** [comment]
wygląda ok, a co robi pusty View()? plus można by pomyśleć czy jak nie ma żadnych filmów o podanej frazie czy nie pokazać jakiegoś napisy "Niestety nie znaleźlićmy żadnego pasującego filmu"

**Comment by wisniewski-patryk** [comment]
👍
